project:
  type: website
  render:
    - "*.qmd"
    - "!publications/_template/"

website:
  title: "Horizon Lab"
  navbar:
    #logo: images/lab.png
    background: "#F6F5F3"
    left:
      - href: index.qmd
        text: Home
      - href: people/index.qmd
        text: People
      - href: research/index.qmd
      - href: publications/index.qmd
      - href: courses/index.qmd
        text: Courses
      - href: https://learnvisualcomputing.github.io/
        text: FoVC Book
      - href: https://yuhaozhu.com/prospective.html
        text: Join Us

  
format:
  html:
    theme:
      - custom.scss
      - cosmo
      - brand
    mainfont: Red Hat Text #Nunito Sans #Optima #
    # css: styles.css
    toc: true



